apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: fastapi-app
    path: patch-deployment.yaml

  # Add the new patch to enable TLS/SSL
  - target:
      kind: Ingress 
      name: fastapi-ingress
    path: patch-ingress-tls.yaml

